name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@v2.0.0