on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: configure git line endings
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v1
      with:
        ref: 9fd21617aee0d73ac10e191ab4b6c5b33789c1dc
    - name: Setup Msys2 environment
      uses: numworks/setup-msys2@v1
      with:
        msystem: MSYS
    - name: Install prerequisites
      run: msys2do pacman -S --noconfirm --noprogressbar --ask=20 perl binutils git make autoconf zip mingw-w64-x86_64-gcc mingw-w64-x86_64-libtool mingw-w64-x86_64-gnutls mingw-w64-x86_64-pkg-config mingw-w64-x86_64-clang
    - name: Install Go 1.13
      run: msys2do pacman -U --noconfirm --noprogressbar --ask=20 http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-go-1.13.8-1-any.pkg.tar.xz
    - name: Build ffmpeg
      run: msys2do ./install_ffmpeg.sh
    - name: Build Livepeer
      run: msys2do ./ci_env.sh make livepeer livepeer_cli
      env:
        CIRCLE_BRANCH: mainnet
    - name: Upload build
      env: 
        CIRCLE_BRANCH: mainnet
        GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
        GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      run: msys2do ./upload_build.sh
