name: Create release on github

on:
  workflow_run:
    workflows:
      - Build binaries
    types:
      - "completed"

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == "tag" && github.event.workflow_run.conclusion == "success" }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Download artifacts from build stage (linux)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts-linux
          path: releases/

      - name: Download artifacts from build stage (windows)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts-windows
          path: releases/

      - name: Download artifacts from build stage (macos)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts-macos
          path: releases/

      - name: Download artifacts from build stage (tensorflow)
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts-linux-tensorflow
          path: releases/

      - name: Generate sha256 checksum and gpg signatures for release artifacts
        uses: livepeer/action-gh-checksum-and-gpg-sign@latest
        with:
          artifacts-dir: releases
          release-name: ${{ github.ref_name }}
          gpg-key: ${{ secrets.CI_GPG_SIGNING_KEY }}
          gpg-key-passphrase: ${{ secrets.CI_GPG_SIGNING_PASSPHRASE }}

      - name: Check releases directory
        shell: bash
        run: |
          cd releases/
          ls -lha *

      - name: Release to github
        if: github.ref_type == "tag"
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            releases/*
